import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ["better-sqlite3"],
  async headers() {
    return [
      {
        // The static JSON files under public/api/ never change between
        // deploys (they're regenerated by `npm run prebuild`), so we let
        // Vercel's edge cache them for a year. The CDN is invalidated on
        // every deploy, so users always get fresh data after a push.
        source: "/api/:path*.json",
        headers: [
          { key: "Cache-Control", value: "public, max-age=3600, s-maxage=31536000, stale-while-revalidate=86400" },
        ],
      },
      {
        // Team logos under /nba-team-logos are immutable.
        source: "/nba-team-logos/:path*",
        headers: [
          { key: "Cache-Control", value: "public, max-age=31536000, immutable" },
        ],
      },
    ];
  },
};

export default nextConfig;
